### ISSUE TITLE
Problema nel visualizzare 2 o 3 grafici 

### ISSUE THREAD

**Issue by philoez98** [giorgiopizz/lab#2]
Provando a plottare 2 o 3 grafici nel canvas, non vengono mostrati correttamente: o ne manca uno, o ne vengono mostrati solo dei pezzi. Non succede con 1 o più di 3 grafici insieme. Probabile problema con cnv_->Divide() o cnv_->cd().
Con 3:
![schermata 2018-11-12 alle 21 37 59](https://user-images.githubusercontent.com/40722053/48373845-4d053c00-e6c3-11e8-8756-74fa23c8a62f.png)
Con 2:
![schermata 2018-11-12 alle 21 39 50](https://user-images.githubusercontent.com/40722053/48373921-88076f80-e6c3-11e8-85a1-c01f5f7c57b2.png)
Ho già provato ad inserire valori a mano nel Divide() ma non cambia nulla, se non solo la disposizione dei pezzi. Fammi sapere se anche tu riscontri lo stesso problema

**Comment by philoez98** [comment]
Allora per ora ho trovato un fix su arch e debian (ma dovrebbe essere uguale anche su Mac, non l'ho testato). Faceva storie con il Divide che avevo impostato all'inizio, quindi ho aggiunto questo al multiplot.cc e sembra coprire abbastanza casi per non avere più problemi.
Nella funzione display(), dalla riga 28. Ecco il testo del fix:

if (n%2 == 0) {
                if (n ==2){
                    cnv_->Divide(n, n/2);
                }else if(n >=4){
                    cnv_->Divide(n/2, n/2);
                }
            }else {
                if(n ==3){
                    cnv_->Divide(n, n/2);
                }else if (n >= 5){
                    cnv_->Divide(n-(n/2), n/2);
                }
            }

Per ora sembra andare, ma la gestione dei subplots va rivista. Domani lo provo su Mac e se tu non hai problemi chiudo la issue e lo aggiungo alla branch phil.

**Comment by giorgiopizz** [comment]
Allora io adesso provo a riscriverla perchè così è un po' macchinos

**Comment by philoez98** [comment]
Si si assolutamente, comunque con quei parametri sembra andare, ma se trovi una soluzione generale molto meglio
